Move to main branch and linting

diff --git a/.github/ci/do_release b/.github/ci/do_release
--- a/.github/ci/do_release
+++ b/.github/ci/do_release
@@ -59,5 +59,5 @@ if [[ $DRY_RUN == 0 ]]; then
 
   git commit --amend -m "Releasing v${TAG}"
   git tag -a "v${TAG}" -m "Version ${TAG}"
-  git push --follow-tags origin master || { echo 'Push failed. git pull --rebase from upstream and attempt another release.'; exit 1; }
+  git push --follow-tags origin main || { echo 'Push failed. git pull --rebase from upstream and attempt another release.'; exit 1; }
 fi
